-- CRIANDO O BANCO DE DADOS
CREATE DATABASE FUNEC2023_DAII;
--@ CHAVE PRIMÁRIA
--# CHAVE ESTRANGEIRA

-- SEXO = {@COD, NOME}
CREATE TABLE SEXO(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(9) NOT NULL UNIQUE
);
--RUA={@COD, NOME}
CREATE TABLE RUA(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(80) NOT NULL UNIQUE
);
--BAIRRO={@COD, NOME}
CREATE TABLE BAIRRO(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(80) NOT NULL UNIQUE
);
--CEP={@COD,NUMERO}
CREATE TABLE CEP(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	NUMERO CHAR(9) NOT NULL UNIQUE
);
--UF={@COD, NOME, SIGLA}
CREATE TABLE UF(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(80) NOT NULL UNIQUE,
	SIGLA CHAR(2) NOT NULL UNIQUE,
);
--CIDADE={@COD, NOME}
CREATE TABLE TRABALHO(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(80) NOT NULL UNIQUE
);
--OPERADORA={@COD, NOME}
CREATE TABLE OPERADORA(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(80) NOT NULL UNIQUE
);
--FUNCAO={@COD, NOME}
CREATE TABLE FUNCAO(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(80) NOT NULL UNIQUE
);
--LOJA={@COD, NOME, CNPJ, NOMEFANTASIA, RAZAOSOCIAL}
CREATE TABLE LOJA(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(80) NOT NULL UNIQUE,
	CNPJ VARCHAR(80) NOT NULL UNIQUE,
	NOMEFANTASIA VARCHAR(80),
	RAZAOSOCIAL VARCHAR(80)
);
--ACESSO={@COD, NOME}
CREATE TABLE ACESSO(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(80) NOT NULL UNIQUE
);
-- MARCA = {@COD, NOME}
CREATE TABLE MARCA(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(80) NOT NULL UNIQUE
);
--TIPO={@COD, NOME}
CREATE TABLE TIPO(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(80) NOT NULL UNIQUE
);
--SITUACAO={@COD, NOME}
CREATE TABLE SITUACAO(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(40) NOT NULL UNIQUE
);
-- Inserindo dados na tabela SEXO
INSERT INTO SEXO (NOME) VALUES
    ('Masculino'),
    ('Feminino'),
    ('Outro'),
    ('Não informado'),
    ('Prefiro não dizer');

-- Inserindo dados na tabela RUA
INSERT INTO RUA (NOME) VALUES
    ('Rua A'),
    ('Rua B'),
    ('Rua C'),
    ('Rua D'),
    ('Rua E');

-- Inserindo dados na tabela BAIRRO
INSERT INTO BAIRRO (NOME) VALUES
    ('Bairro X'),
    ('Bairro Y'),
    ('Bairro Z'),
    ('Bairro W'),
    ('Bairro V');

-- Inserindo dados na tabela CEP
INSERT INTO CEP (NUMERO) VALUES
    ('12345-678'),
    ('98765-432'),
    ('54321-876'),
    ('67890-321'),
    ('23456-789');
-- Inserindo dados na tabela UF
INSERT INTO UF (NOME,SIGLA) VALUES 
	('SÃO PAULO','SP'),
	('RIO DE JANEIRO', 'RJ'),
	('MINAS GERAIS', 'MG'),
	('RIO GRANDE DO SUL', 'RS'),
	('PARANÁ', 'PR');
	INSERT INTO TRABALHO (NOME) VALUES
    ('Vendedor'),
    ('Gerente'),
    ('Analista'),
    ('Engenheiro'),
    ('Desenvolvedor');

-- Inserindo dados na tabela OPERADORA
INSERT INTO OPERADORA (NOME) VALUES
    ('Vivo'),
    ('Tim'),
    ('Claro'),
    ('Oi'),
    ('Nextel');

-- Inserindo dados na tabela FUNCAO
INSERT INTO FUNCAO (NOME) VALUES
    ('Atendimento ao cliente'),
    ('Gestão de equipes'),
    ('Análise de dados'),
    ('Desenvolvimento de software'),
    ('Engenharia de sistemas');
-- Inserindo dados na tabela LOJA
INSERT INTO LOJA (NOME, CNPJ, NOMEFANTASIA, RAZAOSOCIAL) VALUES
    ('Loja A', '12345678901234', 'Fantasia A', 'Razao A'),
    ('Loja B', '98765432109876', 'Fantasia B', 'Razao B'),
    ('Loja C', '45678901234567', 'Fantasia C', 'Razao C'),
    ('Loja D', '32109876543210', 'Fantasia D', 'Razao D'),
    ('Loja E', '78901234567890', 'Fantasia E', 'Razao E');
-- Inserindo dados na tabela ACESSO
INSERT INTO ACESSO (NOME) VALUES
    ('Total'),
    ('Restrito'),
    ('Parcial'),
    ('Administrativo'),
    ('Visitante');
-- Inserindo dados na tabela MARCA
INSERT INTO MARCA (NOME) VALUES
    ('Marca A'),
    ('Marca B'),
    ('Marca C'),
    ('Marca D'),
    ('Marca E');
-- Inserindo dados na tabela TIPO
INSERT INTO TIPO (NOME) VALUES
    ('Eletrônico'),
    ('Vestuário'),
    ('Alimentício'),
    ('Móveis'),
    ('Automotivo');
-- Inserindo dados na tabela SITUACAO
INSERT INTO SITUACAO (NOME) VALUES
    ('Ativo'),
    ('Inativo'),
    ('Em andamento'),
    ('Concluído'),
    ('Pendente');

--CIDADE={@COD, NOME, #CODUF_FK}
CREATE TABLE CIDADE(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(80) NOT NULL UNIQUE,
	CODUF_FK INTEGER REFERENCES UF(COD) ON DELETE CASCADE
	           ON UPDATE CASCADE
);
--CLIENTE={@COD, NOME, FOTO, DATANASC, #CODSEXO_FK, #CODRUA_FK, #CODBAIRRO_FK, #CODCEP_FK, #CODCIDADE_FK, SALARIO, #CODTRABALHO_FK, NUMEROCASA}
CREATE TABLE CLIENTE(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(80) NOT NULL,
	FOTO VARBINARY(MAX),
	DATANASC DATE NOT NULL,
	CODSEXO_FK INTEGER REFERENCES SEXO(COD) ON DELETE CASCADE
	           ON UPDATE CASCADE,
	CODRUA_FK INTEGER REFERENCES RUA(COD) ON DELETE CASCADE
	           ON UPDATE CASCADE,
	CODBAIRRO_FK INTEGER REFERENCES BAIRRO(COD) ON DELETE CASCADE
	           ON UPDATE CASCADE,
	CODCEP_FK INTEGER REFERENCES CEP(COD) ON DELETE CASCADE
	           ON UPDATE CASCADE,
	CODCIDADE_FK INTEGER REFERENCES CIDADE(COD) ON DELETE CASCADE
	           ON UPDATE CASCADE,
	SALARIO NUMERIC(10,2) NOT NULL,
	CODTRABALHO_FK INTEGER REFERENCES TRABALHO(COD) ON DELETE CASCADE
	           ON UPDATE CASCADE,
	NUMEROCASA VARCHAR(30) NOT NULL,   
);
--SELECT 
--    c.COD,
--    c.NOME,
--    c.FOTO,
--    c.DATANASC,
--    sx.Nome AS Sexo,
--    rua.Nome AS Rua,
--    bairro.Nome AS Bairro,
--    cep.NUMERO AS CEP,
--    cidade.Nome AS Cidade,
--    c.SALARIO,
--    trabalho.Nome AS Trabalho,
--    c.NUMEROCASA
--FROM CLIENTE c
--INNER JOIN SEXO sx ON c.CODSEXO_FK = sx.COD
--INNER JOIN RUA rua ON c.CODRUA_FK = rua.COD
--INNER JOIN BAIRRO bairro ON c.CODBAIRRO_FK = bairro.COD
--INNER JOIN CEP cep ON c.CODCEP_FK = cep.COD
--INNER JOIN CIDADE cidade ON c.CODCIDADE_FK = cidade.COD
--INNER JOIN TRABALHO trabalho ON c.CODTRABALHO_FK = trabalho.COD;
-- TELEFONE={@CODTELEFONE, NUMEROTELEFONE}
--TELEFONE={@COD, NUMERO, #CODCLIENTE_FK}
CREATE TABLE TELEFONE(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	NUMERO VARCHAR(14) NOT NULL UNIQUE,
	CODOPERADORA_FK INTEGER REFERENCES OPERADORA(COD) ON DELETE CASCADE
	           ON UPDATE CASCADE,
);
-- VENDA = {@CODVENDA, DATAVENDA, CODCLIENTE_FK}
CREATE TABLE VENDA(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	DATAVENDA DATE NOT NULL,
	CODCLIENTE_FK INTEGER REFERENCES CLIENTE(COD) ON DELETE CASCADE
	              ON UPDATE CASCADE
);
--FUNCIONARIO={@COD, NOME, NUMEROCASA, #CODRUA_FK, #CODBAIRRO_FK, #CODCEP_FK, #CODCIDADE_FK, #CODFUNCAO_FK, SALARIO, #CODLOJA_FK}
CREATE TABLE FUNCIONARIO(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(80) NOT NULL,
	NUMEROCASA VARCHAR(30) NOT NULL,
	CODRUA_FK INTEGER REFERENCES RUA(COD) ON DELETE CASCADE
	           ON UPDATE CASCADE,
	CODBAIRRO_FK INTEGER REFERENCES BAIRRO(COD) ON DELETE CASCADE
	           ON UPDATE CASCADE,
	CODCEP_FK INTEGER REFERENCES CEP(COD) ON DELETE CASCADE
	           ON UPDATE CASCADE,
	CODCIDADE_FK INTEGER REFERENCES CIDADE(COD) ON DELETE CASCADE
	           ON UPDATE CASCADE,
	CODFUNCAO_FK INTEGER REFERENCES FUNCAO(COD) ON DELETE CASCADE
	           ON UPDATE CASCADE,
	SALARIO NUMERIC(10,2) NOT NULL,
	CODLOJA_FK INTEGER REFERENCES LOJA(COD) ON DELETE CASCADE
	           ON UPDATE CASCADE,
);
--LOGINS = {@COD, NOME, SENHA, #CODFUNCIONARIO_FK}
CREATE TABLE LOGINS(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(80) NOT NULL,
	SENHA VARCHAR(80) NOT NULL,
	CODFUNCIONARIO_FK INTEGER REFERENCES FUNCIONARIO(COD) ON DELETE CASCADE
	           ON UPDATE CASCADE
);
--CONTROLELOGINSSISTEMA={@COD, #CODLOGINS_FK, DATAS, HORA}
CREATE TABLE CONTROLELOGINSSISTEMA(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	CODLOGINS_FK INTEGER REFERENCES LOGINS(COD) ON DELETE CASCADE
			ON UPDATE CASCADE,
	DATAS DATE NOT NULL,
	HORA TIME NOT NULL
);
-- Inserindo dados na tabela CONTROLELOGINSSISTEMA
INSERT INTO CONTROLELOGINSSISTEMA (CODLOGINS_FK, DATAS, HORA) VALUES
    (1, '2023-11-29', '08:30:00'),
    (1, '2023-11-29', '10:15:00'),
    (1, '2023-11-29', '12:00:00'),
    (1, '2023-11-30', '09:00:00'),
    (1, '2023-11-30', '14:45:00');
-- TIPO_PRODUTO={@CODTIPOPRODUTO, NOMETIPOPRODUTO}
CREATE TABLE TIPOPRODUTO(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(80) NOT NULL UNIQUE
);

--PRODUTO={@CODPRODUTO, NOMEPRODUTO, QUANT, VALOR, CODMARCA_FK, CODTIPOPRODUTO_FK}
CREATE TABLE PRODUTO(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(80) NOT NULL,
	QUANT NUMERIC(10,2) NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	CODMARCA_FK INTEGER REFERENCES MARCA(COD) ON DELETE CASCADE
	            ON UPDATE CASCADE,
	CODTIPOPRODUTO_FK INTEGER REFERENCES TIPOPRODUTO(COD) 
	                  ON DELETE CASCADE ON UPDATE CASCADE
);

-- VENDAPRODUTO={@(CODVENDA_FK, CODPRODUTO_FK), QUANTV, VALORV}
CREATE TABLE VENDAPRODUTO(
	CODVENDA_FK INTEGER REFERENCES VENDA(COD) ON DELETE CASCADE
	            ON UPDATE CASCADE,
	CODPRODUTO_FK INTEGER REFERENCES PRODUTO(COD) ON DELETE CASCADE
	            ON UPDATE CASCADE,
	QUANTV NUMERIC(10,2) NOT NULL,
	VALORV NUMERIC(10,2) NOT NULL,
	PRIMARY KEY(CODVENDA_FK, CODPRODUTO_FK)
);

--FOTOPRODUTO={@CODFOTO, DESCRICAO, IMAGEM, CODPRODUTO_FK}
CREATE TABLE FOTOPRODUTO(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	DESCRICAO VARCHAR(255) NOT NULL,
	IMAGEM VARBINARY(MAX) NOT NULL,
	CODPRODUTO_FK INTEGER REFERENCES PRODUTO(COD) ON DELETE CASCADE
	              ON UPDATE CASCADE
);


--PARCELAVENDA={@CODPARCELA, DATAVENCIMENTO, VALORPARCELA, CODSITUACAO_FK
--CODVENDA_FK}
CREATE TABLE PARCELAVENDA(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	DATAVENCIMENTO DATE NOT NULL,
	VALORPARCELA NUMERIC(10,2) NOT NULL,
	CODSITUACAO_FK INTEGER REFERENCES SITUACAO(COD) ON DELETE CASCADE
	               ON UPDATE CASCADE, 
	CODVENDA_FK INTEGER REFERENCES VENDA(COD) ON DELETE CASCADE
	               ON UPDATE CASCADE
);


-- FORNECEDOR = {@CODFORNECEDOR, NOMEFORNECEDOR, CNPJ}
CREATE TABLE FORNECEDOR(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(80) NOT NULL,
	CNPJ CHAR(18) NOT NULL UNIQUE --XX.XXX.XXX/0001-XX.
);

--COMPRA={@CODCOMPRA, DATACOMPRA, CODFORNECEDOR_FK}
CREATE TABLE COMPRA(
	COD INTEGER IDENTITY(1,1) PRIMARY KEY,
	DATACOMPRA DATE NOT NULL,
	CODFORNECEDOR_FK INTEGER REFERENCES FORNECEDOR (COD) ON DELETE
	                 CASCADE ON UPDATE CASCADE
);

--COMPRAPRODUTO={@(CODCOMPRA_FK,CODPRODUTO_FK), QUANTC, VALORC}
CREATE TABLE COMPRAPRODUTO(
	CODCOMPRA_FK INTEGER REFERENCES COMPRA(COD)  ON DELETE
	             CASCADE ON UPDATE CASCADE,
	CODPRODUTO_FK INTEGER REFERENCES PRODUTO(COD)  ON DELETE
	             CASCADE ON UPDATE CASCADE,
	QUANTC NUMERIC(10,2) NOT NULL,
	VALORC NUMERIC(10,2) NOT NULL,
	PRIMARY KEY(CODCOMPRA_FK, CODPRODUTO_FK)
);
--11) ITENSTELCLIENTE = {CODTELEFONE, CODCLIENTE}
CREATE TABLE ITENSTELCLIENTE(
	CODTELEFONE INTEGER REFERENCES TELEFONE(COD)  ON DELETE
	             CASCADE ON UPDATE CASCADE,
	CODCLIENTE INTEGER REFERENCES CLIENTE(COD)  ON DELETE
	             CASCADE ON UPDATE CASCADE,
	PRIMARY KEY(CODTELEFONE, CODCLIENTE)
);